### ISSUE TITLE
Calculations not triggered in manage results view

### ISSUE THREAD

**Issue by ramonski** [senaite/bika.lims#355] opened 2017-11-05 09:23 UTC
## Steps to reproduce

- Create 3 Analyses Services with the keywords `length`, `height`, `width`
- Create a Calculation `calc-edgelength` with the formula: `4 * ([length] + [height] + [width])`
- Create another Analysis Service with the keyword `edgelength` and assign the calculation `calc-edgelength` to it
- Create a new AR and assign the 4 Analyses `length`, `height`, `width`, `edgelength` to it
- Receive the sample
- Add the results `1`, `2`, `3` to the  `length`, `height`, `width` result fields

## Current behavior

The result for `edgelength` is not calculated

## Expected behavior

The result of `edgelength` is calculated to `24`

## Screenshot (optional)

![manage_analyses](https://user-images.githubusercontent.com/713193/32413475-44e28234-c212-11e7-8bf3-83fb757078a6.jpg)

![calculation](https://user-images.githubusercontent.com/713193/32413531-4d1ebdb8-c213-11e7-9b44-09d10d01b2f3.jpg)

**Comment by grulisco** [comment] 2017-11-05 11:55
Proper description. Calculations seem to be not triggered by result entry.
But calculations within an AS triggered by interim fields are working correctly.

**Comment by grulisco** [comment] 2017-11-06 09:41
The demo at senaite.ridingbytes.com also shows a defective calculation currently.
See simple Total Hardness Calc (e.g. H2O-0004-R01).

**Comment by grulisco** [comment] 2017-11-06 15:51
Maybe a duplicate of bikalims/bika.lims#2202?

**Comment by ramonski** [comment] 2017-11-07 11:09
Thanks @Espurna, please don't close it yet until we got the feedback from @grulisco.

It seems that this also happens on https://senaite.ridingbytes.com/clients/client-6/H2O-0004-R01/manage_results (labman1:labman1).

@grulisco could you please check if this setup I described in this issue actually reproduce the behavior on your server or did I miss something?

**Comment by grulisco** [comment] 2017-11-07 11:17
Please keep it open. 
See https://senaite.ridingbytes.com/clients/client-6/H2O-0004-R01/manage_results:
![spectacle hz8132](https://user-images.githubusercontent.com/25460329/32490968-48f302f0-c3b5-11e7-8710-ef6dbe243aad.png)
Simple addition does not work.

The testcase (length, width, ...) described is translated from my setup correctly, and still does not work properly.

**Comment by grulisco** [comment] 2017-11-20 16:32
still a problem with senaite 1.1.6

**Comment by xispa** [comment] 2017-11-23 15:33
Although the problem persists in *old* Analysis Requests, it works as expected when creating new Analysis Requests. I've tested the instance after the upgrade 1.6.6. @grulisco can you confirm that if you create a new Analysis Request and select the same analyses, this issue does not happen?

**Technical overview**
To obtain the analyses to which a given analysis depends on to calculate its result, ultimately relies on `calculation.getDependentServices` function. And here is the problem: [`DependentServices` field from `Calculation` was changed from a `HistoryAwareReferenceField` to an `UIDReferenceField` on Nov 2](https://github.com/senaite/bika.lims/pull/279/commits/3da0afa99a336e4221b4636640bd0836099bf0a4#diff-a0f1b1f9deb06b65e2757b10a8e62b45L57). The instance you are using was probably updated after this commit and this relationship was lost.

**Comment by grulisco** [comment] 2017-11-23 17:08
@xispa I'm still on 1.1.6 :) But, in my instance calculations still are not triggered even with new ARs. 
(same in senaite.ridingbytes...)
Expecting latest update by @ramonski tomorrow...

**Comment by xispa** [comment] 2017-11-23 17:39
@grulisco can  you try to go to Kantenlaengen's calculation view and press the save button first. After that, try to create a new AR

**Comment by grulisco** [comment] 2017-11-24 09:12
@xispa Yes it does work, after updating the calculations!
So it seems, that this issue affects not only old ARs but old calcultations too...

**Comment by xispa** [comment] 2017-11-24 15:42
I've done some modifs to the upgrade step 1.1.6 to deal with those broken calcs in Analyses from old Analysis Requests that were not using the latest version of Calculation in https://github.com/senaite/bika.lims/pull/403 , so rerunning 1.1.6 will make the calculations work in old ARs too.

**Closed** 2017-11-28 14:30 UTC
Labels: issue-done, priority: high
