### ISSUE TITLE
Dependencies error in Manage Analyses view

### ISSUE THREAD

**Issue by Espurna** [senaite/bika.lims#357] opened 2017-11-06 17:45 UTC
## Steps to reproduce
**Using senaite.lims**
- Create one Analysis Services with the keywords `one`
- Create a Calculation `calc1` with the formula: `4 * one`
- Create another Analysis Service with the keyword `two` and assign the calculation `calc1` to it
- Create a new AR and assign the both Analyses to it
- Go to Manage Analyses view inside that Analysis Request
- Uncheck analysis `one`.

## Current behavior

Analysis `two` isn't unchecked and the system gives the following error:

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at calcdependencies (bika.lims.analysisrequest.js:542)
    at HTMLInputElement.<anonymous> (bika.lims.analysisrequest.js:673)
    at HTMLDocument.dispatch (jquery-1.12.4.min.js:3)
    at HTMLDocument.r.handle (jquery-1.12.4.min.js:3)
```

## Expected behavior

Analysis `two` should be unchecked since depends on analysis `one`.

**Comment by ramonski** [comment] 2017-11-07 05:24
I think if we have https://github.com/senaite/bika.lims/issues/300 (AR mass editing based on AR Add2) in place, we could use that form (or at least the Analyses picker) instead of the whole "Manage Analyses" form. AR Add2 should resolve these dependencies properly.
However, in the meantime we have to fix that somehow in JS...

Well reproduced and spotted @Espurna!

**Comment by grulisco** [comment] 2017-11-20 16:29
still a problem with senaite 1.1.6

**Comment by xispa** [comment] 2017-12-20 23:44
@Espurna @grulisco @ramonski what about this one... is still there?

**Comment by grulisco** [comment] 2017-12-21 16:32
@xispa: I have no problems since 1.1.8

**Comment by ramonski** [comment] 2017-12-21 22:01
Thanks @grulisco for the feedback. Closing this issue.

**Closed by ramonski** 2017-12-21 22:01 UTC
Labels: bugfix, priority: high
